# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-18 18:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_remove_user_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='trips',
            new_name='Trip',
        ),
    ]
